name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  http: ^0.13.6 # HTTP-запросы к API
  url_launcher: ^6.1.12 # открытие ссылки на статью в браузере
  shared_preferences: ^2.2.2 # хранение состояния
  flutter_riverpod: ^2.4.0
  firebase_core: ^2.30.0 # Основной пакет для инициализации Firebase
  firebase_auth: ^4.17.0 # Пакет для аутентификации Firebase
  cloud_firestore: ^4.15.0 # Пакет для БД Firebase
  firebase_analytics: ^10.8.0 # Пакет для аналитики Firebase
  intl: ^0.19.0 # Пакет для форматирования дат и чисел
  fl_chart: ^0.65.0
  provider: ^6.1.1
  google_fonts: ^4.0.4

dependency_overrides:
  shared_preferences_web: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


